### ISSUE TITLE
Suggest to loosen the dependency on rqalpha

### ISSUE THREAD

**Issue by Agnes-U** [andylokandy/rqalpha-mod-minute#1]
Hi, your project rqalpha-mod-minute(commit id: 0e7f7596b03f33440574dedd8b23bc4bb62c7f4f) requires "rqalpha>=2.3.0" in its dependency. After analyzing the source code, we found that the following versions of rqalpha can also be suitable, i.e., rqalpha 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, since all functions that you directly (3 APIs: rqalpha.interface.AbstractMod.__init__, rqalpha.data.adjust.adjust_bars, rqalpha.data.base_data_source.BaseDataSource.__init__) or indirectly (propagate to 12 rqalpha's internal APIs and 11 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on rqalpha from "rqalpha>=2.3.0" to "rqalpha>=2.2.0". This will improve the applicability of rqalpha-mod-minute and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on rqalpha?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by andylokandy** [comment]
Hey, thanks for the suggestion. I really appreciate your input. If you're interested, I'd love it if you could submit a pull request with your proposed changes. This would allow me to review and consider your suggestion in more detail. Thanks!

> By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

thanks for the suggestion about the automatic tool for dependency analysis. I appreciate the thought, but at the moment we don't have anything like that in place. My advice would be to test any proposed changes locally before submitting a pull request. This will help make sure everything works as intended and avoid any potential problems.

**Comment by Agnes-U** [comment]
Thanks for your kind reply! Here's the PR #2
